docs/constitution/_category_.yml
docs/constitution/constitution.mdx
docs/tutorials/_category_.yml

constitution

---

docs/roles/spo.mdx

Updating spo section with introductory text

Update spo section

---

docs/tutorials/faucet.mdx
docusaurus.config.js
package-lock.json
package.json
src/components/Faucet/RecaptchaField.tsx
src/components/Faucet/index.tsx
src/components/Faucet/styles.module.css

This PR builds upon #6 and adds the complete faucet forms from https://faucet.sanchonet.world.dev.cardano.org/basic-fauce.
I have rebased the one commit from #6 on top of the main branch. I'll keep this branch in sync by rebasing on top of main whenever the target branch gets updated.
**TODO**:

feat: port faucet

---

docs/governance-actions/_category_.yml
docs/governance-actions/actions.mdx
docs/governance-actions/create-actions.mdx
docs/governance-actions/voting-actions.mdx
docs/tutorials/_category_.yml
docs/tutorials/create-action.mdx
docs/tutorials/faucet.mdx
docs/tutorials/keys-and-address.mdx
docs/tutorials/register-spo.mdx
docs/tutorials/start-a-node.mdx
docs/tutorials/vote-actions.mdx

Create actions and vote tutorials. Note that these are very likely to change on the next releases of the node so these will need to be updated

Actions and votes tutorials

---

docusaurus.config.js
src/pages/disclaimer.mdx

disclaimer

---

docs/get-started/get-started.mdx

Missed punctuation, deleted repetition, one typo.

Minor tweaks to get-started.mdx

---

src/theme/Footer/Layout/styles.module.css

This should fix the bad footer on mobile devices, it seems I used some syntax that is actually supported in development but gets mangled in stricter prod build.

fix: Footer folding on mobile

---

docusaurus.config.js
package-lock.json
package.json
src/analytics/AnalyticsContext.tsx
src/analytics/TrackRoute.tsx
src/analytics/osano.ts
src/analytics/useHasConsent.tsx
src/theme/Root.tsx

This PR adds Posthog for analytics.
TODO:

feat: add posthog

---

docs/roles/dev.mdx
docs/roles/drep.mdx
docs/roles/spo.mdx

- fixing typo on spo section
- making dev and drep sections steps similar to those on spo section

fix small typo

---

.github/workflows/deploy.yml

* Initial launch of sancho.network site

CNAME: set to sancho.network

---

README.md

updated to https://sancho.network/
The old link https://sanchonet.network/ didn't resolve.

Update README.md to correct website link for Sancho net

---

docs/get-started/discord.mdx

- Added mention of wallets-sanchonet discord channel and bi-weekly open hour call.

docs: add wallets-sanchonet discord channel and open hour call

---

docs/tutorials/create-action.mdx

- Aligned with changes from` cardano-cli 8.8.0.0`
- Removed the stake key signature from governance action example

docs: Updated gov action example

---

docs/tutorials/actions.mdx

Fixed some typo we found while recording our videos.

Corrections | Governance action guide

---

docs/roles/drep.mdx

Updated the link for DReps to use  to latest version of SanchNet cardano node 8.5.0-pre

Update drep.mdx to link 8.5.0-pre

---

docs/tutorials/jq-filters.mdx

New section. jq filters

---

docs/tools-resources/faq.mdx
docs/tools-resources/resources.mdx

- Updated the DB-Sync links to the most recent Sancho version, on the Resources page.
- Updated the FAQ with recent changes to the Ledger design.

Docs: Updated DB-Sync links on Resources page and added recent CDDL changes to FAQ page

---

docs/tools-resources/resources.mdx

On the resources page:
- Updated DB-Sync and Conway CDDL links
- Added CIP-95 NuFi wallet build link
- Added Ogmios Release Candidate link
N/A

docs: add/ update links on resources page

---

docs/tutorials/actions.mdx
docs/tutorials/jq-filters.mdx
docs/tutorials/queries.mdx

update tutorials for cardano-node 8.6 and cardano-cli 8.13

---

docs/tools-resources/resources.mdx

- change resources page links to reflect CSL alpha 13

Update resources page with csl alpha 13

---

docs/tools-resources/resources.mdx

- Updated DB-Sync links on resources page
- Updated to reflect the merger of CIP-105

update DB-Sync ver and CIP-105 merge

---

docs/get-started/discord.mdx
docs/get-started/govtool.mdx
docs/tools-resources/resources.mdx
docs/tutorials/file-naming-convention.mdx
docs/tutorials/start-a-node.mdx
static/img/header.png:Zone.Identifier

- Added page for Sancho GovTool Beta
- Added Sancho GovTool beta links to resource page
- Reordered the tutorials section to make more sense

docs: Added information for Sancho GovTool Beta

---

docs/meetups.md
docs/tutorials/actions.mdx
docs/tutorials/register-drep.mdx
docs/tutorials/register-spo.mdx
docs/tutorials/vote-actions.mdx

- Fixed a some typo
- Replaced query commands for governance actions
- Replaced some command's value by a query command to always get the right value if protocol parameters change.

Contribution

---

docs/tools-resources/resources.mdx

- adding Cexplorer SanchoNet to resources page

docs: add cexplorer to resources page

---

docs/tutorials/actions.mdx

- fixed cardano cli commands for the governance action tutorial (good spot @rickymac68)
- added some extra context around metadata anchors

Governance action tutorial fixes spotted by @rickymac68

---

docs/tools-resources/resources.mdx

Propose to include Cardano SDK in the list of resources.
Lace is using it for all blockchain-related actions, including serialization and deserialization of CBOR data.

Added cardano-sdk to the list of resources

---

docs/tutorials/actions.mdx
docs/tutorials/register-drep.mdx
docs/tutorials/register-spo.mdx
docs/tutorials/register-stake.mdx

- Updated query commands to get the value of stake key deposit, DRep key deposit and governance action deposit.
- Updated `--quorum` flag for `--threshold` in all "Update committee commands.
- Fixed some typos

Tutorial update for Node V8.10.0 and CLI V8.22.0.0 

---

docs/tutorials/vote-actions-multisig-drep.mdx

Fix capitalization

---

docs/tutorials/register-multisig-drep.mdx
docs/tutorials/vote-actions-multisig-drep.mdx

- added missing flags
- fixed typo

DRep multi-sig tutorial corrections

---

docs/meetups.md
docs/tutorials/actions.mdx
docs/tutorials/committee.mdx
docs/tutorials/register-multisig-drep.mdx
docs/tutorials/vote-actions-multisig-drep.mdx
docs/tutorials/vote-actions.mdx

- Updated commands to be compatible with the latest version of cardano-cli
- Updated the meetups page

SanchoNet tutorial update
