- docs/tutorials/register-spo.mdx
Add required parameter to stake-address registration-certificate command in docs.
Without this parameter, the following error is returned when running the `cardano-cli stake-address registration-certificate` with `--conway-era`:
`Command failed: stake-address registration-certificate  Error: StakeAddressRegistrationDepositRequired`
This is now a required parameter according to [this code](https://github.com/input-output-hk/cardano-cli/blob/f2b12c514ccc6e95b6b688e17c1eea8abafef228/cardano-cli/src/Cardano/CLI/Legacy/Run/StakeAddress.hs#L116)
> Docs: add required parameter to registration cert command

- docs/tutorials/vote-actions.mdx
There is missing quotes in this command.  The dash symbol is otherwise interpreted as a comment by the shell.
> Fix governance vote create-vote example

- .vscode/settings.json
- docs/tutorials/create-action.mdx
- docs/tutorials/delegate-to-drep.mdx
- docs/tutorials/file-naming-convention.mdx
- docs/tutorials/keys-and-address.mdx
- docs/tutorials/register-drep.mdx
- docs/tutorials/register-spo.mdx
- docs/tutorials/register-stake.md
- docs/tutorials/start-a-node.mdx
- docs/tutorials/vote-actions.mdx
Soon we will have 8.3.0-pre available for SanchoNet. This will bring some changes to the CLI,  therefore we need to update the tutorials. Key changes: 
- Any stake key can create a governance action, not only spos as before
- We can register/unregister DReps  in SanchoNet
- Vote delegation to DReps is now possible in SanchoNet
- Voting as DRep is now possible  in SanchoNet
- No need to specify the role when issuing a vote, it is now automatically derived from the key type. 
- Adding query to ledger state to get information about governance actions (next release will bring specific queries) 
- Outline how to validate that the URL and the HASH of a governance action match
> update tutorials for 8.3 [Do not merge until 8.3.0-pre is out]

- docs/tutorials/register-spo.mdx
These are the changes I had to make in order to successfully register JUNGLE (`pool1zscq0y0lwy3vhqkxfnqfk62unezqqx77ck8yf9ezvwjr5azsyks`) on Sanchonet after the most recent reset.
Using cardano-cli 8.10.0.0 and cardano-node 8.4.0
> Update SPO registration docs for cardano-node 8.4.0 and cardano-cli 8.10.0.0

- docs/tools-resources/resources.mdx
* Added Sancho Testnet Guides and Command Line Interface playlist to the Guides from the community.
* I think this is appropriate to have a link to the playlist to avoid having to make a PR every time we make a new video about the Sancho testnet.
> Adding a YouTube Sanchonet Guides playlist

- docs/tools-resources/resources.mdx
Updated the resources + tooling page:
- Added "Last update" note
- Added link to 1694
- Updated CIP-95 link to be the merged one
- Added link for new "DRep Keys CIP"
- Updated links to CSL alpha 10
- Added latest DB-Sync release
> Docs: Updated resources page

- docs/tutorials/delegate-to-drep.mdx
--conway-era no longer needed, removed it from the transaction build
> Removed --conway-era option from DRep Reg Procedure

- docs/tools-resources/resources.mdx
- Changed the `/tools-resources/resources` to align with release of CSL alpha 11
> Docs: update resources page with CSL alpha 11

- docs/tools-resources/resources.mdx
Adding GH link to cardano-signer, which can now also generate dRep keys with mnemonic-support.
> Update resources.mdx - Adding Cardano-Signer to Community Tools

- docs/tutorials/actions.mdx
`cardano-cli` was missing at the Info GA section
> Add 'cardano-cli' to Info GA

- docs/tutorials/register-stake.mdx
The original value from genesis no longer works.
This reflects the up-to-date value since protocol change gov-action.
```bash
cardano-cli conway stake-address registration-certificate \
--stake-verification-key-file stake.vkey \
--key-reg-deposit-amt $(cardano-cli conway query gov-state --testnet-magic 4 | jq -r .enactState.curPParams.keyDeposit) \
--out-file registration.cert
```
Thanks to [Mike Hornan from ABLE pool](https://twitter.com/Hornan7)
> Docs: Update stake registration deposit amount.

- docs/meetups.md
- docs/tutorials/actions.mdx
- docs/tutorials/vote-actions.mdx
- Fixed typo in `transaction build` command.
- Separated commands from their outputs (for easier copy/paste).
- Used `govActDeposit` Variable for the first `update-committee` governance action to demonstrate that it can be used this way. (As it is right now, Line 82 is giving no output on terminal as a variable).
- Fixed a typo in `query gov-state` command.
- Add discord meetups every thursdays.
> Typo Corrections, and meetups

- docs/get-started/get-started.mdx
- docs/tools-resources/resources.mdx
- docs/tutorials/delegate-to-drep.mdx
- docs/tutorials/keys-and-address.mdx
- docs/tutorials/register-spo.mdx
- docs/tutorials/start-a-node.mdx
IOG style guide discourages the use of the phrase 'test ada'. The suggestion is to replace such mentions (and I found just one example) with 'testnet token'.  This PR also suggests replacing tAda with a testnet token. If we're talking about the ticker name, should it be 'tADA' then? This PR also suggests minor additional tweaks.
> Additional style guide edits

- docs/tutorials/file-naming-convention.mdx
changed the examples from `drep_id1...` to `drep1...` because the `_id` was removed
> Update file-naming-convention.mdx (DRepID)

- docs/tools-resources/resources.mdx
Adds Plutarch to the community tools list. Plutarch is a Haskell eDSL for writing on-chain scripts that aims to be fast and fine-tunable than its alternatives. Currently V1 and V2 PlutusLedger is supported, but V3 is in development under Intersect grant.
> Add Plutarch to "tools by the community" list

- docs/roles/dev.mdx
- docs/roles/drep.mdx
- docs/tools-resources/resources.mdx
- docs/tutorials/start-a-node.mdx
- add link to new Node version
- update link for CSL
- add link to govtool repo
- add new DBSync tag
- fix small typo
- add off-chain metadata standards
> docs: update resources page with new Node and tools

- docs/tutorials/delegate-to-drep.mdx
- docs/tutorials/queries.mdx
- docs/tutorials/register-multisig-drep.mdx
- docs/tutorials/vote-actions-multisig-drep.mdx
This adds tutorials for:
- register multisignature drep using native scripts
- delegate to a script-based (multisig) drep
- vote with a multisignature DRep
> register a multisignature drep using native scripts.

- docs/drep-pioneer-program/participation-reqs.mdx
1. Remove requirement for cardano-cli for participants as they can use the GovTool in sancho net. This is also in line with the training program content created for the DRep Training Programme. 
2. The participants can use any CIP-95 comaptible wallet. Need not be Lace wallet itself. 
3. Added a note for reliable internet connection for attending the DRep training in online mode.
> Update participation requirements.

- docs/tools-resources/resources.mdx
[This](http://ec2-16-171-11-232.eu-north-1.compute.amazonaws.com:8080/) is a tool my team developed to be added to the GovTools. I would like to have this listed on the docs so people can find it easier.
> add new link for Constitution checker tool

- docusaurus.config.js
In scraping - returning a lot of redirects from links being output without trailing slashes - this config should resolve that issue
> filip(fix): add config for trailing slashes
